class StringConstant {
  //Login
  static const String ERROR_LOGIN_USER_NOT_FOUND = "User not found !";
  static const String SUCCESS_LOGIN = "Login success !";
  static const String ERROR_PREFIX_LOGIN = "Login||";
  //static const String DEFAULT_LOGIN_USERNAME = "+6281793675512";
  //static const String DEFAULT_LOGIN_PASSWORD = "Test1190";
  static const String DEFAULT_LOGIN_USERNAME = "+6282257168699";
  static const String DEFAULT_LOGIN_PASSWORD = "Hehehe12345";

  //Register
  static const String ERROR_REGISTER_UNABLE_VERIFY_PHONE_NUMBER =
      "Phone number verification failed !";
  static const String SUCCESS_REGISTER = "Register success !";
  static const String DEFAULT_REGISTER_PHONE = "+6282257168699";
  static const String DEFAULT_REGISTER_EMAIL = "daniel12@gmail.com";
  static const String DEFAULT_REGISTER_FULLNAME = "daniel12";
  static const String DEFAULT_REGISTER_PASSWORD = "Test1190";
  static const String LABEL_BUTTON_REGISTER = "Berikutnya";

  //Register Continuation
  static const String ERROR_REGISTER_FAILED = "Register failed !";

  //Reset Password
  static const String ERROR_PREFIX_RESET_PASSWORD = "ResetPassword||";
  static const String ERROR_RESET_PASSWORD_USER_NOT_FOUND = "User not found !";
  static const String SUCCESS_RESET_PASSWORD = "Reset password success !";
  static const String ERROR_RESET_PASSWORD_FAILED = "Reset password failed !";
  static const String ERROR_RESET_PASSWORD_FAILED_PASSWORD_NOT_VALID =
      "Password not valid !";
  static const String DEFAULT_RESET_PASSWORD_PHONE = "+6282257168699";
  static const String DEFAULT_RESET_PASSWORD_NEW_PASSWORD = "Hehehe12345";

  //Snackbar
  static const String SNACKBAR_ACTION_POSITIVE_OK = "OK";

  //KEY-String For Testing Purpose
  static const String KEY_LOGIN_TEXTFIELD_USERNAME = "login_textfield_username";
  static const String KEY_LOGIN_TEXTFIELD_PASSWORD = "login_textfield_password";
  static const String KEY_LOGIN_TEXT_RESET_PASSWORD = "KEY_LOGIN_TEXT_RESET_PASSWORD";
  static const String KEY_LOGIN_TEXT_REGISTER = "KEY_LOGIN_TEXT_REGISTER";
  static const String KEY_LOGIN_BUTTON_LOGIN = "KEY_LOGIN_BUTTON_LOGIN";
  static const String KEY_CATALOG_APPBAR = "catalog_appbar";

  static const String KEY_RESET_PASSWORD_TEXTFIELD_PHONENUMBER =
      "RESET_PASSWORD_TEXTFIELD_PHONENUMBER";

  static const String KEY_AFTER_RESET_PASSWORD_TEXTFIELD_VERIFICATION_CODE =
      "AFTER_RESET_PASSWORD_TEXTFIELD_VERIFICATION_CODE";
  static const String KEY_AFTER_RESET_PASSWORD_TEXTFIELD_NEW_PASSWORD =
      "AFTER_RESET_PASSWORD_TEXTFIELD_NEW_PASSWORD";

  static const String KEY_REGISTER_TEXTFIELD_FULLNAME =
      "KEY_REGISTER_TEXTFIELD_FULLNAME";
  static const String KEY_REGISTER_TEXTFIELD_EMAIL =
      "KEY_REGISTER_TEXTFIELD_EMAIL";
  static const String KEY_REGISTER_TEXTFIELD_PHONE =
      "KEY_REGISTER_TEXTFIELD_PHONE";
  static const String KEY_REGISTER_CHECKBOX_TnC = "KEY_REGISTER_CHECKBOX_TnC";

  static const String KEY_AFTER_REGISTER_TEXTFIELD_PASSWORD =
      "KEY_AFTER_REGISTER_TEXTFIELD_PASSWORD";

  static const String KEY_BIODATA_IMAGE_PICK_AND_TAKE_PHOTO =
      "KEY_BIODATA_IMAGE_PICK_AND_TAKE_PHOTO";
  static const String KEY_BIODATA_CHECKBOX_MALE = "KEY_BIODATA_CHECKBOX_MALE";
  static const String KEY_BIODATA_CHECKBOX_FEMALE =
      "KEY_BIODATA_CHECKBOX_FEMALE";
  static const String KEY_BIODATA_BUTTON_SELECT_DATE =
      "KEY_BIODATA_BUTTON_SELECT_DATE";
  static const String KEY_BIODATA_BUTTON_SEND = "KEY_BIODATA_BUTTON_SEND";

  // HOME CONTAINER
  static const String KEY_HOME_IMAGE_EVENT = "KEY_HOME_IMAGE_EVENT";
  static const String KEY_HOME_IMAGE_NO_EVENT = "KEY_HOME_IMAGE_NO_EVENT";
  static const String KEY_HOME_IMAGE_NEW_PRODUCT_CARDS =
      "KEY_HOME_IMAGE_NEW_PRODUCT_CARDS";
  static const String KEY_HOME_TEXT_NEW_PRODUCT_SEE_ALL =
      "KEY_HOME_TEXT_NEW_PRODUCT_SEE_ALL";
  static const String KEY_HOME_LIST_EVENT_IMAGE = "KEY_HOME_LIST_EVENT_IMAGE";
  static const String KEY_HOME_TAP_TO_RETRY_LIST_EVENT_IMAGE = "KEY_HOME_TAP_TO_RETRY_LIST_EVENT_IMAGE";
  static const String KEY_HOME_LIST_NEW_PRODUCTS = "KEY_HOME_LIST_NEW_PRODUCTS";
  static const String KEY_HOME_TAP_TO_RETRY_LIST_NEW_PRODUCTS = "KEY_HOME_TAP_TO_RETRY_LIST_NEW_PRODUCTS";
  static const String KEY_HOME_SLIVERLIST_NEW_PRODUCT = "KEY_HOME_SLIVERLIST_NEW_PRODUCT";

  // DETAIL EVENT
  static const String KEY_DETAIL_EVENT_IMAGE_EVENT =
      "KEY_DETAIL_EVENT_IMAGE_EVENT";
  static const String KEY_DETAIL_EVENT_BUTTON_BACK =
      "KEY_DETAIL_EVENT_BUTTON_BACK";
  static const String KEY_DETAIL_EVENT_TITLE = "KEY_DETAIL_EVENT_TITLE";
  static const String KEY_DETAIL_EVENT_DESCRIPTION =
      "KEY_DETAIL_EVENT_DESCRIPTION";

  //DETAIL PICTURE
  static const String KEY_DETAIL_PICTURE_BUTTON_BACK =
      "KEY_DETAIL_PICTURE_BUTTON_BACK";
  static const String KEY_DETAIL_PICTURE_IMAGE = "KEY_DETAIL_PICTURE_IMAGE";

  static const String KEY_NEW_PRODUCT_CATALOG_BUTTON_BACK =
      "KEY_NEW_PRODUCT_CATALOG_BUTTON_BACK";
  static const String KEY_NEW_PRODUCT_CATALOG_BUTTON_SEARCH =
      "KEY_NEW_PRODUCT_CATALOG_BUTTON_SEARCH";
  static const String KEY_NEW_PRODUCT_CATALOG_BUTTON_SHOPPING_CART =
      "KEY_NEW_PRODUCT_CATALOG_BUTTON_SHOPPING_CART";
  static const String KEY_NEW_PRODUCT_CATALOG_GRID_VIEW =
      "KEY_NEW_PRODUCT_CATALOG_GRID_VIEW";
  static const String KEY_NEW_PRODUCT_CATALOG_LIST_VIEW =
      "KEY_NEW_PRODUCT_CATALOG_LIST_VIEW";
  static const String KEY_NEW_PRODUCT_CATALOG_BUTTON_SWAP_VIEW =
      "KEY_NEW_PRODUCT_CATALOG_BUTTON_SWAP_VIEW";

  // CATALOG NEW PRODUCT PADA HOME
  static const String KEY_PARENT_CATALOG_NEW_PRODUCT_BUTTON_BACK =
      "KEY_PARENT_CATALOG_NEW_PRODUCT_BUTTON_BACK";
  static const String KEY_PARENT_CATALOG_NEW_PRODUCT_BUTTON_ADD_TO_CART =
      "KEY_PARENT_CATALOG_NEW_PRODUCT_BUTTON_ADD_TO_CART";

  // DETAIL CATALOG
  static const String KEY_DETAIL_CATALOG_IMAGE =
      "KEY_DETAIL_CATALOG_IMAGE_SLIDER";
  static const String KEY_DETAIL_CATALOG_BUTTON_ADD_TO_CART =
      "KEY_DETAIL_CATALOG_BUTTON_ADD_TO_CART";
  static const String KEY_DETAIL_CATALOG_BUTTON_BACK =
      "KEY_DETAIL_CATALOG_BUTTON_BACK";
  static const String KEY_DETAIL_CATALOG_TEXT_ART_DATA =
      "KEY_DETAIL_CATALOG_TEXT_ART_DATA";
  static const String KEY_DETAIL_CATALOG_TEXT_DESCRIPTION =
      "KEY_DETAIL_CATALOG_TEXT_DESCRIPTION";
  static const String KEY_DETAIL_CATALOG_TEXT_CERTIFICATE_NUM =
      "KEY_DETAIL_CATALOG_TEXT_CERTIFICATE_NUM";
  static const String KEY_DETAIL_CATALOG_TEXT_SALE_PRICE =
      "KEY_DETAIL_CATALOG_TEXT_SALE_PRICE";
  static const String KEY_DETAIL_CATALOG_ICON_WISHLIST_UNFAVORITE =
      "KEY_DETAIL_CATALOG_ICON_WISHLIST_UNFAVORITE";
  static const String KEY_DETAIL_CATALOG_ICON_WISHLIST_LOADING =
      "KEY_DETAIL_CATALOG_ICON_WISHLIST_LOADING";
  static const String KEY_DETAIL_CATALOG_ICON_WISHLIST_FAVORITE =
      "KEY_DETAIL_CATALOG_ICON_WISHLIST_FAVORITE";

  static const String KEY_DETAIL_CATALOG_TEXT_PRODUCT_NAME =
      "KEY_DETAIL_CATALOG_TEXT_PRODUCT_NAME";
  static const String KEY_DETAIL_CATALOG_TEXT_MEDIA =
      "KEY_DETAIL_CATALOG_TEXT_MEDIA";
  static const String KEY_DETAIL_CATALOG_TEXT_ARTIST =
      "KEY_DETAIL_CATALOG_TEXT_ARTIST";

  // MY COLLECTION
  static const String KEY_MY_COLLECTION_IMAGE_CBATIK =
      "KEY_MY_COLLECTION_IMAGE_CBATIK";
  static const String KEY_MY_COLLECTION_IMAGE_COLECTION_STATUE =
      "KEY_MY_COLLECTION_IMAGE_COLECTION_STATUE";
  static const String KEY_MY_COLLECTION_TEXT_COLLECTION_EMPTY =
      "KEY_MY_COLLECTION_TEXT_COLLECTION_EMPTY";
  static const String KEY_MY_COLLECTION_TEXT_LETS_BUY_ART_PRODUCT =
      "KEY_MY_COLLECTION_TEXT_LETS_BUY_ART_PRODUCT";
  static const String KEY_MY_COLLECTION_ICON_VIEW_MODE_GRID =
      "KEY_MY_COLLECTION_ICON_VIEW_MODE_GRID";
  static const String KEY_MY_COLLECTION_ICON_VIEW_MODE_LIST =
      "KEY_MY_COLLECTION_ICON_VIEW_MODE_LIST";
  static const String KEY_MY_COLLECTION_CARD_GET_PRODUCT_RECOMENDATION =
      "KEY_MY_COLLECTION_CARD_GET_PRODUCT_RECOMENDATION";
  static const String KEY_MY_COLLECTION_TEXT_GET_PRODUCT_RECOMENDATION_NAME =
      "KEY_MY_COLLECTION_TEXT_GET_PRODUCT_RECOMENDATION_NAME";
  static const String KEY_MY_COLLECTION_TEXT_GET_PRODUCT_RECOMENDATION_CODE =
      "KEY_MY_COLLECTION_TEXT_GET_PRODUCT_RECOMENDATION_CODE";
  static const String KEY_MY_COLLECTION_TEXT_GET_PRODUCT_RECOMENDATION_PRICE =
      "KEY_MY_COLLECTION_TEXT_GET_PRODUCT_RECOMENDATION_PRICE";

  // DETAIL MY COLLECTION
  static const String KEY_DETAIL_MY_COLLECTION_IMAGE =
      "KEY_DETAIL_MY_COLLECTION_IMAGE";
  static const String KEY_DETAIL_MY_COLLECTION_BUTTON_PINTA =
      "KEY_DETAIL_MY_COLLECTION_BUTTON_PINTA";
  static const String KEY_DETAIL_MY_COLLECTION_BUTTON_BACK =
      "KEY_DETAIL_MY_COLLECTION_BUTTON_BACK";
  static const String KEY_DETAIL_MY_COLLECTION_TEXT_ART_DATA =
      "KEY_DETAIL_MY_COLLECTION_TEXT_ART_DATA";
  static const String KEY_DETAIL_MY_COLLECTION_TEXT_NAME=
      "KEY_DETAIL_MY_COLLECTION_TEXT_NAME";
  static const String KEY_DETAIL_MY_COLLECTION_TEXT_CERTIFICATE_NUM =
      "KEY_DETAIL_MY_COLLECTION_TEXT_CERTIFICATE_NUM";
  static const String KEY_DETAIL_MY_COLLECTION_TEXT_SALE_PRICE =
      "KEY_DETAIL_MY_COLLECTION_TEXT_SALE_PRICE";
  static const String KEY_DETAIL_MY_COLLECTION_ICON_UNFAVORITE =
      "KEY_DETAIL_MY_COLLECTION_ICON_UNFAVORITE";
  static const String KEY_DETAIL_MY_COLLECTION_ICON_FAVORITE_LOADING =
      "KEY_DETAIL_MY_COLLECTION_ICON_FAVORITE_LOADING";
  static const String KEY_DETAIL_MY_COLLECTION_ICON_FAVORITE =
      "KEY_DETAIL_MY_COLLECTION_ICON_FAVORITE";

  static const String KEY_DETAIL_MY_COLLECTION_TEXT_ARTIST =
      "KEY_DETAIL_MY_COLLECTION_TEXT_ARTIST";

  static const String KEY_DETAIL_MY_COLLECTION_TEXT_MEDIA =
      "KEY_DETAIL_MY_COLLECTION_TEXT_MEDIA";

  static const String KEY_DETAIL_MY_COLLECTION_TEXT_DESCRIPTION=
      "KEY_DETAIL_MY_COLLECTION_ICON_FAVORITE";

  // GRID MY COLLECTION
  static const String KEY_MY_COLLECTION_GRID_CARD =
      "KEY_MY_COLLECTION_GRID_CARD";
  static const String KEY_MY_COLLECTION_GRID_IMAGE =
      "KEY_MY_COLLECTION_GRID_IMAGE";
  static const String KEY_MY_COLLECTION_GRID_ICON_FAVORITE =
      "KEY_MY_COLLECTION_GRID_ICON_FAVORITE";
  static const String KEY_MY_COLLECTION_GRID_ICON_PROGRESS_FAVORITE =
      "KEY_MY_COLLECTION_GRID_ICON_PROGRESS_FAVORITE";
  static const String KEY_MY_COLLECTION_GRID_ICON_UNFAVORITE =
      "KEY_MY_COLLECTION_GRID_ICON_UNFAVORITE";
  static const String KEY_MY_COLLECTION_GRID_TEXT_COLLECTION_NAME =
      "KEY_MY_COLLECTION_GRID_TEXT_COLLECTION_NAME";
  static const String KEY_MY_COLLECTION_GRID_TEXT_COLLECTION_CERT_ID =
      "KEY_MY_COLLECTION_GRID_TEXT_COLLECTION_CERT_ID";
  static const String KEY_MY_COLLECTION_GRID_ICON_PINTA =
      "KEY_MY_COLLECTION_GRID_ICON_PINTA";

  // LIST MY COLLECTION
  static const String KEY_MY_COLLECTION_LIST_CARD =
      "KEY_MY_COLLECTION_LIST_CARD";
  static const String KEY_MY_COLLECTION_LIST_IMAGE =
      "KEY_MY_COLLECTION_LIST_IMAGE";
  static const String KEY_MY_COLLECTION_LIST_ICON_FAVORITE =
      "KEY_MY_COLLECTION_LIST_ICON_FAVORITE";
  static const String KEY_MY_COLLECTION_LIST_ICON_PROGRESS_FAVORITE =
      "KEY_MY_COLLECTION_LIST_ICON_PROGRESS_FAVORITE";
  static const String KEY_MY_COLLECTION_LIST_ICON_UNFAVORITE =
      "KEY_MY_COLLECTION_LIST_ICON_UNFAVORITE";
  static const String KEY_MY_COLLECTION_LIST_TEXT_COLLECTION_NAME =
      "KEY_MY_COLLECTION_LIST_TEXT_COLLECTION_NAME";
  static const String KEY_MY_COLLECTION_LIST_TEXT_COLLECTION_CERT_ID =
      "KEY_MY_COLLECTION_LIST_TEXT_COLLECTION_CERT_ID";
  static const String KEY_MY_COLLECTION_LIST_ICON_PINTA =
      "KEY_MY_COLLECTION_LIST_ICON_PINTA";
  static const String KEY_MY_COLLECTION_LIST_RECOMMENDATION =
      "KEY_MY_COLLECTION_LIST_RECOMMENDATION";
  static const String KEY_MY_COLLECTION_LIST_RECOMMENDATION_CONTAINER =
      "KEY_MY_COLLECTION_LIST_RECOMMENDATION_CONTAINER";
  static const String KEY_MY_COLLECTION_LIST_FAVORITE =
      "KEY_MY_COLLECTION_LIST_FAVORITE";

  // HOMEPAGE
  static const String KEY_HOMEPAGE_ICON_HANDLER_DRAWER_MENU =
      "KEY_HOMEPAGE_ICON_HANDLER_DRAWER_MENU";
  static const String KEY_HOMEPAGE_TABVIEW_COLLECTION =
      "KEY_HOMEPAGE_TABVIEW_COLLECTION";
  static const String KEY_HOMEPAGE_TABVIEW_CATALOG =
      "KEY_HOMEPAGE_TABVIEW_CATALOG";
  static const String KEY_HOMEPAGE_TABVIEW_HOME = "KEY_HOMEPAGE_TABVIEW_HOME";
  static const String KEY_HOMEPAGE_DRAWER_HOME = "KEY_HOMEPAGE_DRAWER_HOME";
  static const String KEY_HOMEPAGE_DRAWER_ORDER_HISTORY =
      "KEY_HOMEPAGE_DRAWER_ORDER_HISTORY";
  static const String KEY_HOMEPAGE_DRAWER_ABOUT = "KEY_HOMEPAGE_DRAWER_ABOUT";
  static const String KEY_HOMEPAGE_DRAWER_CATALOG =
      "KEY_HOMEPAGE_DRAWER_CATALOG";
  static const String KEY_HOMEPAGE_DRAWER_EVENT = "KEY_HOMEPAGE_DRAWER_EVENT";
  static const String KEY_HOMEPAGE_DRAWER_COLLECTION =
      "KEY_HOMEPAGE_DRAWER_COLLECTION";
  static const String KEY_HOMEPAGE_DRAWER_INBOX =
      "KEY_HOMEPAGE_DRAWER_INBOX";
  static const String KEY_HOMEPAGE_DRAWER_IMAGE_CONECTIZEN_GO_TO_MY_PROFILE =
      "KEY_HOMEPAGE_DRAWER_IMAGE_CONECTIZEN_GO_TO_MY_PROFILE";
  static const String KEY_HOMEPAGE_DRAWER_CART_BUTTON_GO_TO_SHOPPING_CART_UI =
      "KEY_HOMEPAGE_DRAWER_CART_BUTTON_GO_TO_SHOPPING_CART_UI";

  // SHOPPING CART UI
  static const String KEY_SHOPPING_CART_UI_BUTTON_PAYOUT =
      "KEY_SHOPPING_CART_UI_BUTTON_PAYOUT";
  static const String KEY_SHOPPING_CART_UI_BUTTON_PROCESS =
      "KEY_SHOPPING_CART_UI_BUTTON_PROCESS";
  static const String KEY_SHOPPING_CART_UI_BUTTON_BACK =
      "KEY_SHOPPING_CART_UI_BUTTON_BACK";
  static const String KEY_SHOPPING_CART_UI_BUTTON_DELETE =
      "KEY_SHOPPING_CART_UI_BUTTON_DELETE";
  static const String KEY_SHOPPING_CART_UI_CHECKBOX_DELETE =
      "KEY_SHOPPING_CART_UI_CHECKBOX_DELETE";
  static const String KEY_SHOPPING_CART_UI_CARD_RECOMENDATION =
      "KEY_SHOPPING_CART_UI_CARD_RECOMENDATION";
  static const String KEY_SHOPPING_CART_UI_CARD_LIST_CARD =
      "KEY_SHOPPING_CART_UI_CARD_LIST_CARD";
  static const String KEY_SHOPPING_CART_UI_TEXT_DELETE =
      "KEY_SHOPPING_CART_UI_TEXT_DELETE";
  static const String KEY_SHOPPING_CART_ICON_ADD_MORE =
      "KEY_SHOPPING_CART_ICON_ADD_MORE";
  static const String KEY_SHOPPING_CART_LIST =
      "KEY_SHOPPING_CART_LIST";
  static const String KEY_SHOPPING_CART_LIST_RECOMMENDATION =
      "KEY_SHOPPING_CART_LIST_RECOMMENDATION";
  static const String KEY_SHOPPING_CART_LIST_RECOMMENDATION_CONTAINER =
      "KEY_SHOPPING_CART_LIST_RECOMMENDATION_CONTAINER";

  //PAYOUT.DART
  static const String KEY_PAYOUT_TRANSACTION_BUTTON_OK =
      "KEY_PAYOUT_TRANSACTION_BUTTON_OK";
  static const String KEY_PAYOUT_TRANSACTION_BUTTON_PINTA_SUCCESS =
      "KEY_PAYOUT_TRANSACTION_BUTTON_PINTA_SUCCESS";

  //CATALOG
  static const String KEY_CATALOG_SLIVERGRID =
      "KEY_CATALOG_SLIVERGRID";
  static const String KEY_CATALOG_SLIVERLIST =
      "KEY_CATALOG_SLIVERGRID";
  static const String KEY_CATALOG_ICON_VIEW_MODE_GRID =
      "KEY_CATALOG_ICON_VIEW_MODE_GRID";
  static const String KEY_CATALOG_ICON_VIEW_MODE_LIST =
      "KEY_CATALOG_ICON_VIEW_MODE_LIST";
  static const String KEY_CATALOG_ICON_FILTER =
      "KEY_CATALOG_ICON_FILTER";
  static const String KEY_CATALOG_BUTTON_GO_UP =
      "KEY_CATALOG_BUTTON_GO_UP";
  static const String KEY_CATALOG_CUSTOMSCROLLVIEW =
      "KEY_CATALOG_CUSTOMSCROLLVIEW";

  //CATALOG FILTER
  static const String KEY_CATALOG_FILTER_BUTTON_EXPENSIVE_TO_CHEAP_BUTTON =
      "KEY_CATALOG_FILTER_BUTTON_EXPENSIVE_TO_CHEAP_BUTTON";
  static const String KEY_CATALOG_FILTER_BUTTON_CHEAP_TO_EXPENSIVE_BUTTON =
      "KEY_CATALOG_FILTER_BUTTON_CHEAP_TO_EXPENSIVE_BUTTON";
  static const String KEY_CATALOG_FILTER_BUTTON_APRECIATION_DESC =
      "KEY_CATALOG_FILTER_BUTTON_APRECIATION_DESC";
  static const String KEY_CATALOG_FILTER_BUTTON_APRECIATION_ASC =
      "KEY_CATALOG_FILTER_BUTTON_APRECIATION_ASC";

  static const String KEY_CATALOG_FILTER_TEXTFIELD_MINIMAL_PRICE =
      "KEY_CATALOG_FILTER_TEXTFIELD_MINIMAL_PRICE";
  static const String KEY_CATALOG_FILTER_TEXTFIELD_MAXIMAL_PRICE =
      "KEY_CATALOG_FILTER_TEXTFIELD_MAXIMAL_PRICE";

  static const String KEY_CATALOG_FILTER_BUTTON_OK =
      "KEY_CATALOG_FILTER_BUTTON_OK";
  static const String KEY_CATALOG_FILTER_BUTTON_FILTER_NOT_VALID =
      "KEY_CATALOG_FILTER_BUTTON_FILTER_NOT_VALID";


  static const String KEY_CATALOG_FILTER_BUTTON_CATEGORY =
      "KEY_CATALOG_FILTER_BUTTON_CATEGORY";

  //CATALOG GRID
  static const String KEY_CATALOG_GRID_CARD =
      "KEY_CATALOG_GRID_CARD";
  static const String KEY_CATALOG_GRID_IMAGE =
      "KEY_CATALOG_GRID_IMAGE";
  static const String KEY_CATALOG_GRID_ICON_WISHLIST =
      "KEY_CATALOG_GRID_ICON_WISHLIST";
  static const String KEY_CATALOG_GRID_ICON_PROGRESS_WISHLIST =
      "KEY_CATALOG_GRID_ICON_PROGRESS_WISHLIST";
  static const String KEY_CATALOG_GRID_ICON_UNWISHLIST=
      "KEY_CATALOG_GRID_ICON_UNWISHLIST";
  static const String KEY_CATALOG_GRID_TEXT_CATALOG_NAME =
      "KEY_CATALOG_GRID_TEXT_CATALOG_NAME";
  static const String KEY_CATALOG_GRID_TEXT_CATALOG_PRICE =
      "KEY_CATALOG_GRID_TEXT_CATALOG_PRICE";
  static const String KEY_CATALOG_GRID_ICON_ADD_TO_CART =
      "KEY_CATALOG_GRID_ICON_ADD_TO_CART";

  //CATALOG LIST
  static const String KEY_CATALOG_LIST_CARD =
      "KEY_CATALOG_LIST_CARD";
  static const String KEY_CATALOG_LIST_IMAGE =
      "KEY_CATALOG_LIST_IMAGE";
  static const String KEY_CATALOG_LIST_ICON_WISHLIST =
      "KEY_CATALOG_LIST_ICON_WISHLIST";
  static const String KEY_CATALOG_LIST_ICON_PROGRESS_WISHLIST =
      "KEY_CATALOG_LIST_ICON_PROGRESS_WISHLIST";
  static const String KEY_CATALOG_LIST_ICON_UNWISHLIST=
      "KEY_CATALOG_LIST_ICON_UNWISHLIST";
  static const String KEY_CATALOG_LIST_TEXT_CATALOG_NAME =
      "KEY_CATALOG_LIST_TEXT_CATALOG_NAME";
  static const String KEY_CATALOG_LIST_TEXT_CATALOG_PRICE =
      "KEY_CATALOG_LIST_TEXT_CATALOG_PRICE";
  static const String KEY_CATALOG_LIST_ICON_ADD_TO_CART =
      "KEY_CATALOG_LIST_ICON_ADD_TO_CART";

  //ABOUT
  static const String KEY_ABOUT_IMAGE_CANTIQUE =
      "KEY_ABOUT_IMAGE_CANTIQUE";
  static const String KEY_ABOUT_TEXT_ADDRESS =
      "KEY_ABOUT_TEXT_ADDRESS";
  static const String KEY_ABOUT_TEXT_PHONE =
      "KEY_ABOUT_TEXT_PHONE";
  static const String KEY_ABOUT_ICONBUTTON_WA =
      "KEY_ABOUT_ICONBUTTON_WA";
  static const String KEY_ABOUT_ICONBUTTON_PHONE =
      "KEY_ABOUT_ICONBUTTON_PHONE";

  // ORDER HISTORY
  static const String KEY_ORDER_HISTORY_LIST =
      "KEY_ORDER_HISTORY_LIST";
  static const String KEY_ORDER_HISTORY_IMAGE=
      "KEY_ORDER_HISTORY_IMAGE";
  static const String KEY_ORDER_HISTORY_TEXT_DATE =
      "KEY_ORDER_HISTORY_TEXT_DATE";
  static const String KEY_ORDER_HISTORY_TEXT_CO =
      "KEY_ORDER_HISTORY_TEXT_CO";
  static const String KEY_ORDER_HISTORY_TEXT_PRICE =
      "KEY_ORDER_HISTORY_TEXT_PRICE";
  static const String KEY_ORDER_HISTORY_TEXT_SEE_DETAIL=
      "KEY_ORDER_HISTORY_TEXT_SEE_DETAIL";
  static const String KEY_ORDER_HISTORY_DETAIL_IMAGE=
      "KEY_ORDER_HISTORY_DETAIL_IMAGE";
  static const String KEY_ORDER_HISTORY_DETAIL_TEXT_NAME=
      "KEY_ORDER_HISTORY_DETAIL_TEXT_NAME";
  static const String KEY_ORDER_HISTORY_DETAIL_TEXT_ID=
      "KEY_ORDER_HISTORY_DETAIL_TEXT_ID";
  static const String KEY_ORDER_HISTORY_DETAIL_TEXT_PRICE=
      "KEY_ORDER_HISTORY_DETAIL_TEXT_PRICE";
  static const String KEY_ORDER_HISTORY_DETAIL_BUTTON_CLOSE=
      "KEY_ORDER_HISTORY_DETAIL_BUTTON_CLOSE";

  //MY PROFILE
  static const String KEY_MYPROFILE_TEXT_NAME =
      "KEY_MYPROFILE_TEXT_NAME";
  static const String KEY_MYPROFILE_TEXT_EMAIL =
      "KEY_MYPROFILE_TEXT_EMAIL";
  static const String KEY_MYPROFILE_TEXT_PHONE =
      "KEY_MYPROFILE_TEXT_PHONE";
  static const String KEY_MYPROFILE_TEXT_CONECTIZEN_ID =
      "KEY_MYPROFILE_TEXT_CONECTIZEN_ID";
  static const String KEY_MYPROFILE_IMAGE_CONECTIZEN_PHOTO =
      "KEY_MYPROFILE_IMAGE_CONECTIZEN_PHOTO";
  static const String KEY_MYPROFILE_IMAGE_CONECTIZEN_QR_CONECTIZEN_ID =
      "KEY_MYPROFILE_IMAGE_CONECTIZEN_QR_CONECTIZEN_ID";
  static const String KEY_MYPROFILE_BUTTON_BACK =
      "KEY_MYPROFILE_BUTTON_BACK";

  //DRAWER
  static const String KEY_OPENDRAWER_TEXT_NAME =
      "KEY_OPENDRAWER_TEXT_NAME";
  static const String KEY_OPENDRAWER_TEXT_CONECTIZEN_ID =
      "KEY_OPENDRAWER_TEXT_CONECTIZEN_ID";
  static const String KEY_OPENDRAWER_TEXT_PHONE =
      "KEY_OPENDRAWER_TEXT_PHONE";
  static const String KEY_OPENDRAWER_TEXT_EMAIL =
      "KEY_OPENDRAWER_TEXT_EMAIL";
  static const String KEY_OPENDRAWER_TEXT_SIGN_OUT =
      "KEY_OPENDRAWER_TEXT_SIGN_OUT";

  // SEARCH BAR
  static const String KEY_SEARCHBAR_ICON_SEARCH =
      "KEY_SEARCHBAR_ICON_SEARCH";
  static const String KEY_SEARCHBAR_ICON_CLEAR_TEXT =
      "KEY_SEARCHBAR_ICON_CLEAR_TEXT";
  static const String KEY_SEARCHBAR_ICON_BACK_BUTTON=
      "KEY_SEARCHBAR_ICON_BACK_BUTTON";
  static const String KEY_SEARCHBAR_TEXTFIELD_VALUE=
      "SearchBarTextField";

  // GET CONECTIZEN
  static const String KEY_GETCONECTIZEN_TEXTFIELD_CONECTIZEN_ID=
      "KEY_GETCONECTIZEN_TEXTFIELD_CONECTIZEN_ID";
  static const String KEY_GETCONECTIZEN_TEXTFIELD_CONECTIZEN_NAME=
      "KEY_GETCONECTIZEN_TEXTFIELD_CONECTIZEN_NAME";
  static const String KEY_GETCONECTIZEN_TEXTFIELD_CONECTIZEN_PHONE=
      "KEY_GETCONECTIZEN_TEXTFIELD_CONECTIZEN_PHONE";
  static const String KEY_GETCONECTIZEN_ICON_CONECTIZEN_SEARCH=
      "KEY_GETCONECTIZEN_ICON_CONECTIZEN_SEARCH";
  static const String KEY_GETCONECTIZEN_TEXTFIELD_CONECTIZEN_TRANSFER_PRICE=
      "KEY_GETCONECTIZEN_TEXTFIELD_CONECTIZEN_TRANSFER_PRICE";

  static const String KEY_GETCONECTIZEN_CUSTOMSCROLLVIEW=
      "KEY_GETCONECTIZEN_CUSTOMSCROLLVIEW";

  static const String KEY_GETCONECTIZEN_TEXTFIELD_CONECTIZEN_PASSWORD=
      "KEY_GETCONECTIZEN_TEXTFIELD_CONECTIZEN_PASSWORD";
  static const String KEY_GETCONECTIZEN_BUTTON_TRANSFER=
      "KEY_GETCONECTIZEN_BUTTON_TRANSFER";
  static const String KEY_GETCONECTIZEN_DIALOG_INPUT_PASSWORD=
      "KEY_GETCONECTIZEN_DIALOG_INPUT_PASSWORD";
  static const String KEY_GETCONECTIZEN_BUTTON_INPUT_PASSWORD=
      "KEY_GETCONECTIZEN_BUTTON_INPUT_PASSWORD";


  static const String CIRCULARPROGRESSINDICATOR=
      "CIRCULARPROGRESSINDICATOR";

  // inbox
  static const String KEY_INBOX_TAB_MESSAGES=
      "KEY_INBOX_TAB_MESSAGES";
  static const String KEY_INBOX_TAB_NOTIFICATIONS=
      "KEY_INBOX_TAB_NOTIFICATIONS";

  //inbox notif
  static const String KEY_INBOX_NOTIFICATIONS_LIST=
      "KEY_INBOX_NOTIFICATIONS_LIST";
  static const String KEY_INBOX_ICON_ENVELOPE_CLOSE=
      "KEY_INBOX_ICON_ENVELOPE_CLOSE";
  static const String KEY_INBOX_ICON_ENVELOPE_OPEN=
      "KEY_INBOX_ICON_ENVELOPE_OPEN";

  //inbox detail
  static const String KEY_INBOX_NOTIFICATIONS_DETAIL_TEXT_FROM=
      "KEY_INBOX_NOTIFICATIONS_DETAIL_TEXT_FROM";
  static const String KEY_INBOX_NOTIFICATIONS_DETAIL_TEXT_TITLE=
      "KEY_INBOX_NOTIFICATIONS_DETAIL_TEXT_TITLE";
  static const String KEY_INBOX_NOTIFICATIONS_DETAIL_TEXT_DESC=
      "KEY_INBOX_NOTIFICATIONS_DETAIL_TEXT_DESC";
  static const String KEY_INBOX_NOTIFICATIONS_DETAIL_BUTTON_BACK=
      "KEY_INBOX_NOTIFICATIONS_DETAIL_BUTTON_BACK";




  //static const String KEY_CATALOG_WISHLIST_ACTIVE = "KEY_CATALOG_WISHLIST_ACTIVE";
  //static const String KEY_CATALOG_WISHLIST_INACTIVE = "KEY_CATALOG_WISHLIST_INACTIVE";
  static const String KEY_CATALOG_ADD_TO_CART = "KEY_CATALOG_ADD_TO_CART";
  static const String KEY_CATALOG_TOGGLE_GRID_OR_LIST = "KEY_CATALOG_TOGGLE_GRID_OR_LIST";
  static const String KEY_CATALOG_FILTER = "KEY_CATALOG_FILTER";

}
